# Generated by Django 6.1.1 on 2026-10-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardlist',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='board',
            name='background',
            field=models.CharField(default='gradient-ocean', max_length=50),
        ),
        migrations.AddField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('workspace', 'Workspace Visible'), ('public', 'Public')], default='workspace', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='label_color',
            field=models.CharField(blank=True, default='blue', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
